/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false --env-interface=WebBindings apps/web/worker-configuration.d.ts` (hash: 9f542b3d8cc511597bd5c0d7a63c9a59)
interface __BaseEnv_WebBindings {
	ASSETS: Fetcher;
	API: Fetcher /* product-monitor-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare");
	}
	interface Env extends __BaseEnv_WebBindings {}
}
interface WebBindings extends __BaseEnv_WebBindings {}
