/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/api/wrangler.jsonc --include-runtime=false --env-interface=ApiBindings apps/api/worker-configuration.d.ts` (hash: e1f7e7a1f117430a77038398fbb9edb6)
interface __BaseEnv_ApiBindings {
	DATABASE: Hyperdrive;
	PUBLIC_URL: "https://product-monitor.example.com";
	AUTH_PROVIDER: "better-auth";
	EMAIL_PROVIDER: "disabled";
	ENCRYPTION_KEY_VERSION: "v1";
	BUILD_REVISION: "development";
	SOURCE_URL: "https://github.com/arminayat/product-monitor";
	AUTH_SECRET: string;
	ENCRYPTION_KEYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare");
	}
	interface Env extends __BaseEnv_ApiBindings {}
}
interface ApiBindings extends __BaseEnv_ApiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_URL" | "AUTH_PROVIDER" | "EMAIL_PROVIDER" | "ENCRYPTION_KEY_VERSION" | "BUILD_REVISION" | "SOURCE_URL" | "AUTH_SECRET" | "ENCRYPTION_KEYS">> {}
}
